name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.2', '3.1', '3.0', '2.7']
        actionview_version: ['7.0', '6.1']

        include:
          - ruby_version: '2.7'
            actionview_version: '6.0'

          - ruby_version: '2.6'
            actionview_version: '6.1'
          - ruby_version: '2.6'
            actionview_version: '5.2'

          - ruby_version: '2.5'
            actionview_version: '6.1'

          - ruby_version: '2.4'
            actionview_version: '5.2'

          - ruby_version: '2.3'
            actionview_version: '5.2'

          - ruby_version: '2.2'
            actionview_version: '5.2'
          - ruby_version: '2.2'
            actionview_version: '5.1'
          - ruby_version: '2.2'
            actionview_version: '5.0'

    env:
      ACTIONVIEW_VERSION: ${{ matrix.actionview_version }}

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - run: rm -f Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          rubygems: ${{ (matrix.ruby_version < '2.3' && '2.7.11') || (matrix.ruby_version < '2.6' && '3.2.3') || 'latest' }}
          bundler-cache: true
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - run: bundle exec rake
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
